# TITLE
APP_TITLE = "Trim Stuff"

# ENTRIES
FILE_PATH_ENTRY = "File"
CUT_FROM_END_ENTRY = "Cut From End (sec)"
START_FROM_ENTRY = "Start From (sec)"

# BUTTONS
OUTPUT_BUTTON = "Output"
BROWSE_BUTTON = "Browse"
TRIM_BUTTON = "Trim"

# OPTION BOXES
RESOLUTION_OPTION_BOX = "Resolution"

# MESSAGES
LOG_MESSAGE = "Log"

# LABELS
TITLE_LABEL = "Title"

# FRAMES
OPTIONS_FRAME = "Options"
LOG_FRAME = LOG_MESSAGE

# RESOLUTIONS
RES_720 = "1280x720"
RES_1080 = "1920x1080"
SCALING_OPTIONS = [RES_720, RES_1080]

# STRINGS
TIME_PLACEHOLDER = "00:00:00"
SAVE_AS = "Save as..."
